### ISSUE TITLE
При попытке редактирования блога появляется сообщение с исключением

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/alto-plugin-blogsubtitle#1]
При включенном плагине любая попытка неавторизованного участника перейти по ссылке редактирования блога (http://site_name.ru/blog/edit/20/) приводит к появлению сообщения с исключением: Exception: Can not find the template "actions/blog/action.blog.test-blog.tpl" in skin "start-kit". Probably you need to activate plugin "Ls". Если плагин отключить, все работает нормально, появляется страница "Нет доступа".

**Comment by aVadim483** [comment]
Сейчас все нормально? Этой ошибки больше нет?

**Comment by bambarbia-kergudu** [comment]
Ошибка исчезла после обновления. Тикет можно закрывать. Спасибо, Вадим.
