### ISSUE TITLE
При редактировании топика ранее введенная информация не подгружается в тектовое поле "Подзаголовок блога" 

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/alto-plugin-blogsubtitle#2]
Открываем страницу редактирования блога (http://alto1116.ru/blog/edit/2/), заполняем поле "Подзаголовок блога", сохраняем форму. Возвращаемся обратно на страницу редактирования после редиректа в блог. Поле "Подзаголовок блога" пусто, хотя вся ранее введенная инфа доступна для вывода через {$oBlog->getSubtitle()|escape:'html'} и данные сохранены в БД. Если в поле ввести новые данные, то они заменят старые. В логах никаких ошибок нет.

Проверял на Альто 1.1.16. В версии 1.1.13 все работало нормально.

**Comment by aVadim483** [comment]
fixed
